In [3]:
import pandas as pd
import numpy as np

In [5]:
a1 = np.array([2,3,4])
s1 = pd.Series(a1)
print(a1)
print(s1)

[2 3 4]
0    2
1    3
2    4
dtype: int64


In [7]:
a2 = np.arange(10)
s2 = pd.Series(a2)
print(a2)
print(s2)

[0 1 2 3 4 5 6 7 8 9]
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [8]:
s3 = pd.Series(np.random.random(10))
s3

0    0.403728
1    0.189392
2    0.415319
3    0.985384
4    0.954831
5    0.726412
6    0.436419
7    0.107793
8    0.538283
9    0.388726
dtype: float64

In [9]:
np.random.random(10)

array([0.6709382 , 0.99394236, 0.60658742, 0.91139892, 0.48337503,
       0.3787172 , 0.55615444, 0.03528784, 0.70278747, 0.43094393])

In [12]:
df1 = pd.DataFrame([[1,2,3], ['a', 'b', 'c'], [4,5,6]], index=["row1", "row2", "row3"])
df1

0  1  2
row1  1  2  3
row2  a  b  c
row3  4  5  6

In [15]:
ss1 = pd.Series(np.arange(0,3))
ss2 = pd.Series(np.arange(3,6))
ss3 = pd.Series(np.arange(6,9))

df2 = pd.DataFrame([ss1,ss2,ss3])
print(df2)
df3 = pd.DataFrame({"col1":ss1, "col2":ss2, "col3":ss3})
print(df3)

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
   col1  col2  col3
0     0     3     6
1     1     4     7
2     2     5     8


In [16]:
df = pd.DataFrame({"col1": [1, 2, 3], "col2": [4, 5, 6], "col3": [7, 8, 9]},index=["row1","row2","row3"])

In [17]:
df

col1  col2  col3
row1     1     4     7
row2     2     5     8
row3     3     6     9

In [25]:
df['col1']

row1    1
row2    2
row3    3
Name: col1, dtype: int64

In [26]:
df.loc['row1']

col1    1
col2    4
col3    7
Name: row1, dtype: int64

In [27]:
df.describe()

col1  col2  col3
count   3.0   3.0   3.0
mean    2.0   5.0   8.0
std     1.0   1.0   1.0
min     1.0   4.0   7.0
25%     1.5   4.5   7.5
50%     2.0   5.0   8.0
75%     2.5   5.5   8.5
max     3.0   6.0   9.0