In [1]:
import numpy as np

In [2]:
np.arange(9).reshape(3,-1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
a1 = np.array([2,3,4])
print(a1)
print(a1.dtype)

[2 3 4]
int64


In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.empty( (2,3), dtype=int)

array([[              0,               0,               3],
       [              0,               0, 844424930131968]])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(6,10)

array([6, 7, 8, 9])

In [14]:
a2 = np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
a3 = np.arange(12).reshape(4,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
a7 = np.arange(24).reshape(2,3,4)
a7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a = np.array([20,30,40,50])
b = np.array([0,1,2,3])

In [19]:
a-b

array([20, 29, 38, 47])

In [20]:
a*b

array([  0,  30,  80, 150])

In [21]:
a<25

array([ True, False, False, False])

In [22]:
A = np.array([[1,1],[0,1]])
B = np.array([[5,4],[3,4]])
np.dot(A,B)

array([[8, 8],
       [3, 4]])

In [23]:
A*B

array([[5, 4],
       [0, 4]])